name: Run NPX Script

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-npx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run npx command
        run: |
          REDOCLY_ENVIRONMENT=reunite npx @redocly/cli@2.29.1 push ./  \
            --organization "testing_redocly" \
            --project "taras-and-bohdan-onboarding" \
            --mount-path "/testsssss" \
            --domain "https://app.cloud.redocly.com" \
            --wait-for-deployment
            --branch "<Your branch name>" \
            --author "<Your name and email>" \
            --message "<Your commit message>" \
